### ISSUE TITLE
Still not working...

### ISSUE THREAD

**Issue by PUDGE133** [Jesus-QC/BanLogger#2]
![image](https://user-images.githubusercontent.com/47304666/111122736-7c703000-857f-11eb-8511-caab5b68d556.png)

**Comment by Jesus-QC** [comment]
YOU MESSED UP WITH YOUR CONFIGS, ITS NOT A PLUGIN ERROR

**Comment by PUDGE133** [comment]
> YOU MESSED UP WITH YOUR CONFIGS, ITS NOT A PLUGIN ERROR

And in what place do you think the error is?
